# Generated by Django 5.1.1 on 2024-10-25 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_transaction_description_alter_transaction_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='fund',
            field=models.CharField(choices=[('general', 'General'), ('specific', 'Specific')], max_length=20),
        ),
    ]
