# Generated by Django 5.1.1 on 2024-11-04 00:57

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_generaltransaction_project_projecttransaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeneralTransaction',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='goal_end_date',
            new_name='end_date',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='description',
        ),
        migrations.AddField(
            model_name='transaction',
            name='donor_name',
            field=models.CharField(default=datetime.date(2024, 11, 4), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='main.project'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='fund',
            field=models.CharField(default='general', max_length=20),
        ),
        migrations.DeleteModel(
            name='ProjectTransaction',
        ),
    ]
